# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envsim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='humid_state',
            field=models.NullBooleanField(verbose_name='Humid State'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='humid_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Humid Val'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='instant',
            field=models.DateTimeField(auto_now_add=True, unique=True, verbose_name='Instant'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='light_state',
            field=models.NullBooleanField(verbose_name='Light State'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temp_state',
            field=models.NullBooleanField(verbose_name='Temp State'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temp_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Temp Val'),
        ),
    ]
