# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envsim', '0002_auto_20170115_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='humid_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Humid Val'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temp_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temp Val'),
        ),
    ]
