# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envsim', '0003_auto_20170115_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now=True, verbose_name='Instant')),
                ('temp_state', models.BooleanField(verbose_name='Temp State')),
                ('humid_state', models.BooleanField(verbose_name='Humid State')),
                ('light_state', models.BooleanField(verbose_name='Light State')),
            ],
        ),
    ]
