# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envsim', '0007_auto_20170116_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='error',
            field=models.BooleanField(default=False, verbose_name='Error'),
        ),
    ]
