# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envsim', '0008_reading_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='error',
            field=models.BooleanField(verbose_name='Error'),
        ),
    ]
