# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envsim', '0010_config_live_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='live_mode',
            field=models.BooleanField(verbose_name='Live Mode'),
        ),
    ]
