# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envsim', '0013_config_humid_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='humid_length',
            field=models.PositiveIntegerField(default=10, verbose_name='Humid Length'),
        ),
    ]
